[package]
name = "skv_talk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.11"
termion = "1.5.6"
tokio = { version = "1.20.1", features = ["full"] }
